set LIB=%LIBRARY_LIB%;%LIB%
set INCLUDE=%LIBRARY_INC%;%INCLUDE%
set LIBRARY_DIRS=%LIBRARY_BIN%;%LIBRARY_LIB%

set AVIF_ROOT=%LIBRARY_PREFIX%
set JPEG_ROOT=%LIBRARY_PREFIX%
set JPEG2K_ROOT=%LIBRARY_PREFIX%
set ZLIB_ROOT=%LIBRARY_PREFIX%
set TIFF_ROOT=%LIBRARY_PREFIX%
set HARFBUZZ_ROOT=%LIBRARY_PREFIX%
set FREETYPE_ROOT=%LIBRARY_PREFIX%
set LCMS_ROOT=%LIBRARY_PREFIX%
set WEBP_ROOT=%LIBRARY_PREFIX%

set PILLOW_ENABLE_LCMS=1
set PILLOW_ENABLE_WEBP=1
set PILLOW_ENABLE_JPEG2000=1
set PILLOW_ENABLE_ZLIB=1
set PILLOW_ENABLE_JPEG=1
set PILLOW_ENABLE_TIFF=1
set PILLOW_ENABLE_FREETYPE=1
set PILLOW_ENABLE_WEBPMUX=1

%PYTHON% -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
if errorlevel 1 exit 1
