{% set version = "4.1.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://github.com/python-pillow/Pillow/archive/{{ version }}.tar.gz
  sha256: a0fd487fed4a35717401b7566e51a1520b34e7c0f7f2a315a6509f82bc86299f

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - zlib 1.2.*
    - libtiff 4.0.*
    - jpeg 9*
    - freetype 2.7|2.7.*
    - tk 8.5.*
  run:
    - python
    - jpeg 9*
    - zlib 1.2.*
    - freetype 2.7|2.7.*
    - libtiff 4.0.*
    - olefile

test:
  imports:
    - PIL
    - PIL.Image
  commands:
    - conda inspect linkages -p $PREFIX pillow  # [not win]
    - conda inspect objects -p $PREFIX pillow  # [osx]

about:
  home: http://python-imaging.github.io/
  license: PIL
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors.'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
