{% set name = "pillow" %}
{% set version = "12.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c5ae0a06e9ea030ab786b0251b32c7e4ce10e58d983c0d5c56029455180b5b9

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - pybind11
    - setuptools >=77
    # Required by default
    - jpeg {{ jpeg }}
    - zlib {{ zlib }}
    # Optional dependencies
    # (also can be incuded libopenjp2, raqm, libimagequant
    # libxcb, openjpeg (it causes build errors on win32),
    # see https://pillow.readthedocs.io/en/latest/installation/building-from-source.html#external-libraries)
    # A subset of one file of tk is also vendored in.
    - libavif {{ libavif }}
    - freetype {{ freetype }}
    - harfbuzz {{ harfbuzz }}
    - fribidi {{ fribidi }}
    - lcms2 {{ lcms2 }}
    - libtiff {{ libtiff }}
    - libwebp-base {{ libwebp }}
    - libopenjpeg {{ openjpeg }}
    - libxcb {{ libxcb }}  # [linux]
  run:
    - python
    - freetype
    - jpeg
    - libtiff
    - libwebp-base
    - libopenjpeg
    - zlib
    - harfbuzz
    - fribidi
    - libxcb  # [linux]

test:
  source_files:
    - selftest.py
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
    # Testing _imaging to verify that it doesn't fail like reported in https://anaconda.atlassian.net/browse/PKG-5184
    - PIL._imaging
  requires:
    - pip
  commands:
    - pip check
    - python -c "from PIL.Image import core"
    - python selftest.py
    # The upstream Tests/images contains a lot of image files that can be tested by pytest
    # but then the size of the package will increase significantly (+70Mb).
    # Pillow tests against some images that it cannot keep in-repo
    # due to anti-virus software triggering. For a slightly longer explanation, see:
    # https://github.com/conda-forge/pillow-feedstock/pull/104#issuecomment-1005245444

about:
  home: https://pillow.readthedocs.io
  license: HPND AND TCL
  license_family: Other
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: https://pillow.readthedocs.io
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
