{% set version = "3.3.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://github.com/python-pillow/Pillow/archive/{{ version }}.tar.gz
  sha256: ae2fbb500c81100f7e374545d008019e6f90918386f620625c3b3b98faf88414

build:
  number: 0
  script: python setup.py build_ext install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pip
    - zlib 1.2.*
    - libtiff 4.0.6
    - jpeg 9*
    - freetype 2.6.*
    - tk
  run:
    - python
    - jpeg 9*
    - zlib 1.2.*
    - freetype 2.6.*
    - libtiff 4.0.6

test:
  imports:
    - PIL
    - PIL.Image

about:
  home: http://python-imaging.github.io/
  license: Standard PIL license
  summary: "Pillow is the friendly PIL fork by Alex Clark and Contributors."

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
