{% set name = "pillow" %}
{% set version = "9.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pillow-{{ version }}.tar.gz
  sha256: a1c2d7780448eb93fbcc3789bf3916aa5720d942e37945f4056680317f1cd23e
  patches:                  # [unix]
    - disable_detect.patch  # [unix]

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    # Required by default
    - jpeg 9e
    - zlib 1.2.13
    # Optional dependencies
    # (also can be incuded libwebp, libimagequant, libraqm, 
    # libxcb, openjpeg (it causes build errors on win32),
    # see https://pillow.readthedocs.io/en/latest/installation.html#external-libraries)
    - freetype 2.10.4
    - lcms2 2.12       # [not win]
    - libtiff 4.2.0
    - libwebp 1.2.0
    - tk 8.6.12
  run:
    - python
    - freetype >=2.10.4,<3.0a0
    - jpeg >=9e,<10a
    - libtiff >=4.2.0,<5.0a0
    - libwebp >=1.2.0,<1.3.0a0
    - libwebp-base >=1.2.0,<1.3.0a0  # [osx and arm64]
    - tk >=8.6.12,<8.7.0a0
    - zlib >=1.2.13,<1.3.0a0

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_family: Other 
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: https://pillow.readthedocs.io/
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
