{% set version = "4.2.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: 15da23d69748111021ba98bf7f35ef17d0c223a2eff12883c75b2bb68cd2d0b0

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - zlib 1.2.*
    - libtiff 4.0.*
    - jpeg 9*
    - freetype 2.7|2.7.*
    - tk 8.5.*
  run:
    - python
    - jpeg 9*
    - zlib 1.2.*
    - freetype 2.7|2.7.*
    - libtiff 4.0.*
    - olefile

test:
  imports:
    - PIL
    - PIL.Image
  commands:
    - conda inspect linkages -p $PREFIX pillow  # [not win]
    - conda inspect objects -p $PREFIX pillow  # [osx]

about:
  home: http://python-imaging.github.io/
  license: PIL
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors.'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
