{% set name = "pillow" %}
{% set version = "11.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a64dd61998416367b7ef979b73d3a85853ba9bec4c2925f74e588879a58716b6
  patches:  # [osx]
    - patches/osx_sdk_path.patch  # [osx]

build:
  number: 0
  skip: true  # [py<39 or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - patch  # [osx]
  host:
    - python
    - pip
    - setuptools >=77
    # Required by default
    - jpeg {{ jpeg }}
    - zlib {{ zlib }}
    # Optional dependencies
    # (also can be incuded libwebp, libimagequant, libraqm,
    # libxcb, openjpeg (it causes build errors on win32),
    # see https://pillow.readthedocs.io/en/latest/installation/building-from-source.html#external-libraries)
    # A subset of one file of tk is also vendored in.
    - freetype {{ freetype }}
    - lcms2 2.16
    - libtiff {{ libtiff }}
    - libwebp-base {{ libwebp }}
    - openjpeg 2.5.2
  run:
    - python
    - freetype
    - jpeg
    - libtiff
    - libwebp-base
    - openjpeg
    - zlib

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
    # Testing _imaging to verify that it doesn't fail like reported in https://anaconda.atlassian.net/browse/PKG-5184
    - PIL._imaging
  # The upstream Tests/images contains a lot of image files that can be tested by pytest
  # but then the size of the package will increase significantly (+70Mb).
  # Pillow tests against some images that it cannot keep in-repo
  # due to anti-virus software triggering. For a slightly longer explanation, see:
  # https://github.com/conda-forge/pillow-feedstock/pull/104#issuecomment-1005245444
  requires:
    - pip
  commands:
    - pip check
    - "python -c \"from PIL.Image import core\""

about:
  home: https://pillow.readthedocs.io
  license: HPND AND TCL
  license_family: Other
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: https://pillow.readthedocs.io/
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf