{% set version = "3.0.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: ad50bef540fe5518a4653c3820452a881b6a042cb0f8bb7657c491c6bd3654bb

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - zlib 1.2.*
    - libtiff 4.0.*
    - jpeg 9*
    - freetype 2.7|2.7.*
    - tk 8.5.*
  run:
    - python
    - jpeg 9*
    - zlib 1.2.*
    - freetype 2.7|2.7.*
    - libtiff 4.0.*
    - olefile

test:
  imports:
    - PIL
    - PIL.Image
  commands:
    - conda inspect linkages -p $PREFIX pillow  # [not win]
    - conda inspect objects -p $PREFIX pillow  # [osx]

about:
  home: http://python-imaging.github.io/
  license: Standard PIL license
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors.'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
