{% set name = "pillow" %}
{% set version = "10.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d2455fbf44c914840c793e89aa82d0e1763a14253a000743719ae5946814b2d

build:
  number: 0
  skip: true # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=67.8
    - wheel
    # Required by default
    - jpeg 9e
    - zlib 1.2.13
    # Optional dependencies
    # (also can be incuded libwebp, libimagequant, libraqm,
    # libxcb, openjpeg (it causes build errors on win32),
    # see https://pillow.readthedocs.io/en/latest/installation/building-from-source.html#external-libraries)
    # A subset of one file of tk is also vendored in.
    - freetype 2.10.4
    - lcms2 2.12
    - libtiff 4.2.0
    - libwebp-base 1.3.2
    - openjpeg 2.3
  run:
    - python
    - freetype >=2.10.4,<3.0a0
    - jpeg >=9e,<10a
    - libtiff >=4.2.0,<5.0a0
    - libwebp-base >=1.3.2,<2.0a0
    - openjpeg >=2.3.0,<3.0a0
    - zlib >=1.2.13,<1.3.0a0

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
  # The upstream Tests/images contains a lot of image files that can be tested by pytest 
  # but then the size of the package will increase significantly (+70Mb).
  # Pillow tests against some images that it cannot keep in-repo
  # due to anti-virus software triggering. For a slightly longer explanation, see:
  # https://github.com/conda-forge/pillow-feedstock/pull/104#issuecomment-1005245444
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pillow.readthedocs.io
  license: HPND AND TCL
  license_family: Other
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: https://pillow.readthedocs.io/
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
