{% set version = "5.1.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: cee9bc75bff455d317b6947081df0824a8f118de2786dc3d74a3503fd631f4ef

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - zlib 1.2.11
    - libtiff >=4.0.8,<4.0.10
    - jpeg 9*
    - freetype 2.8.1
    - tk 8.6.*
  run:
    - python
    - jpeg 9*
    - zlib 1.2.11
    - freetype 2.8.1
    - libtiff >=4.0.8,<4.0.10
    - olefile
    - tk 8.6.*

test:
  imports:
    - PIL
    - PIL.Image
    - PIL._imaging
    - PIL._imagingft
    - PIL._imagingmath
    - PIL._imagingmorph
    - PIL._imagingtk  # [linux and not (arm or ppc64le)]

  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pillow.readthedocs.io
  license: PIL
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors.'
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: http://pillow.readthedocs.io/en/4.2.x/
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
