{% set name = "pillow" %}
{% set version = "9.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pillow-{{ version }}.tar.gz
  sha256: c935a22a557a560108d780f9a0fc426dd7459940dc54faa49d83249c8d3e760f
  patches:
    - disable_detect.patch  # [unix]
  
build:
  number: 0
  skip: true  # [py<37]
  ignore_run_exports:
    - tk
    - jpeg
    - freetype  # [win]
    - libtiff   # [win]
    - libwebp   # [win]
    - zlib      # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
  host:
    - python
    - pip     
    # 2022/7/14: The issue was observed with 'import PIL.Image' in v9.2.0:
    # Additional double quotes for Core version: "9.2.0" on win-64 for python 3.7 and python 3.8.
    # The last version of pillow we built (v9.0.1) was built using conda-build-3.21.7, 
    # Looking at the conda-build changelog for v3.21.9, it was noticed some changes to support the new setuptools >=60.0
    # Check if the issue persists in the next releases 
    - setuptools <60  # [win and (py==37 or py==38)]
    - setuptools      # [not (win and (py==37 or py==38))]
    - wheel
    # Required by default
    - jpeg
    - zlib
    # Optional dependencies
    # (also can be incuded libwebp, libimagequant, libraqm, 
    # libxcb, openjpeg (it causes build errors on win32),
    # see https://pillow.readthedocs.io/en/latest/installation.html#external-libraries)
    - freetype
    - lcms2  # [not win]
    - libtiff
    - libwebp
    - tk
  run:
    - python
    - freetype
    - jpeg
    - libtiff
    - libwebp >=0.3.0
    - libwebp-base  # [osx and arm64]
    - tk
    - zlib

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_family: Other 
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: https://pillow.readthedocs.io/
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
