{% set version = "3.2.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://github.com/python-pillow/Pillow/archive/{{ version }}.tar.gz
  sha256: eb4b9c2956e38f89d588a0d0af0e27a03f1e1d2be705a828bbd12cfba0b020fa

build:
  number: 2
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
    - zlib 1.2*
    - libtiff 4.0.6
    - jpeg 9*
    - freetype 2.6*
    - tk
  run:
    - python
    - jpeg 9*
    - zlib 1.2*
    - freetype 2.6*
    - libtiff 4.0.6

test:
  imports:
    - PIL
    - PIL.Image

about:
  home: http://python-imaging.github.io/
  license: Standard PIL license
  summary: "Pillow is the friendly PIL fork by Alex Clark and Contributors."

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
