{% set name = "pillow" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pillow-{{ version }}.tar.gz
  sha256: 6c8bc8238a7dfdaf7a75f5ec5a663f4173f8c367e5a39f87e720495e1eed75fa
  patches:                  # [unix]
    - disable_detect.patch  # [unix]

build:
  number: 0
  skip: true  # [py<37]
  ignore_run_exports:
    - tk
    - jpeg
    - libwebp  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
  host:
    - python
    - pip
    - setuptools
    - wheel
    # Required by default
    - jpeg
    - zlib
    # Optional dependencies
    # (also can be incuded libwebp, libimagequant, libraqm, 
    # libxcb, openjpeg (it causes build errors on win32),
    # see https://pillow.readthedocs.io/en/latest/installation.html#external-libraries)
    - freetype
    - lcms2  # [not win]
    - libtiff
    - libwebp
    - tk
  run:
    - python
    - freetype
    - jpeg
    - libtiff
    - libwebp >=0.3.0
    - tk
    - zlib

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
  requires:
    - pip
    - libwebp-base  # [osx and arm64]
  commands:
    - pip check

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_family: Other 
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: https://pillow.readthedocs.io/en/4.2.x/
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
