{% set version = "8.3.1" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: 2cac53839bfc5cece8fdbe7f084d5e3ee61e1303cccc86511d351adcb9e2c792

build:
  number: 0
  skip: true  # [py==27]
  ignore_run_exports:
    - tk
    - jpeg

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    # Required by default
    - zlib
    - jpeg
    # Optional dependencies 
    # (also can be incuded libwebp, libimagequant, libraqm, libxcb,
    # see https://pillow.readthedocs.io/en/latest/installation.html#external-libraries)
    - lcms2  # [not win]
    - libtiff
    - openjpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - openjpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]
    - PIL._imaging
    - PIL._imagingft
    - PIL._imagingmath
    - PIL._imagingmorph
    - PIL._imagingtk  # [linux and not (arm or ppc64le or aarch64)]
  requires:
    - pip
    - requests
    - aiohttp
  commands:
    - pip check

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_family: Other 
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: http://pillow.readthedocs.io/en/4.2.x/
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
